### ISSUE TITLE
Client: Add Abbreviation for Electives shortform in the Semester Page

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#100]
PE - Professional Elective
OE - Open Elective

**Comment by SAD0XER** [comment]
> PE - Professional Elective
> OE - Open Elective

Where should I add these?
can you please elaborate more?

**Comment by kunalkeshan** [comment]
![image](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/68579547/83fdb67f-b0b2-4027-ac88-9adebbc3b365)

Over this part a small note para which includes the abbreviations, @SAD0XER

**Comment by SAD0XER** [comment]
> ![image](https://private-user-images.githubusercontent.com/68579547/287217016-83fdb67f-b0b2-4027-ac88-9adebbc3b365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjA5MjksIm5iZiI6MTcwMTc2MDYyOSwicGF0aCI6Ii82ODU3OTU0Ny8yODcyMTcwMTYtODNmZGI2N2YtYjBiMi00MDI3LWFjODgtOWFkZWJiYzNiMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA3MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZmQ3NThkZjNiZGVhMWRiNjFkN2MwYjY1YmI4YmY0ZDAyMjk0NWRiNGI0MjcyOTE5YmVmODQ0MmJmYjY0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqaNumKdyK8apZMitYX0xZBdhiE0s1pkUFBfS72-BxY)
> 
> Over this part a small note para which includes the abbreviations, @SAD0XER

@kunalkeshan, Actually I was trying to understand this project.
So, correct me if I'm wrong.

`semester.jsx` is the base file for semester pages and those `semInfo.jsx` and `CourseInfo.jsx` are rendered on the 'semester.jsx' file. Right?

So, I have to write **Abbreviation** code inside the 'semester.jsx' file below the `semester info` and `course Info` placeholders.

*Look at the photo to understand what I am saying.*

![WhatsApp Image 2023-12-05 at 13 53 13](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/79737447/35bcf8f1-6101-4390-b16c-2601f627a89f)

**Please guide man, I am a very newbie in Open Source :sweat_smile:**
