### ISSUE TITLE
`Client`: Update Semester 1 to redirect to specific Drive Folder

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#116]

**Comment by SAD0XER** [comment]
# Let's Start From Issue 1. :smile:

I have understood all 6 Issues.

[Here](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/blob/client/src/data/semesters.json), within a `driveLink` key I need to add links of a respective folder as `value`.

**AM I RIGHT?**

**Comment by kunalkeshan** [comment]
Yep, that's right, more like just update it to the respective folder. 
You'll have to do a bit of navigation in the drive and copy/pasting the updated URL for each semester.

**Comment by SAD0XER** [comment]
### :sweat_smile: This is a little off-topic :
I have contributed to this project so why is GitHub not showing me as a contributor?

_Maybe the reason is, at the very end of PR you make some changes and commit, so GitHub feels like it was you, who made some changes!_

_That's why they won't update that. Who Knows!_:lying_face:

**Comment by SAD0XER** [comment]
Okay, then I will contribute in your `main` README.

Like,
- Fixing feedback link.
- Increase the header size of "Table of Content".
- Centering alignment of those GitHub star badges, etc.
- etc.

> I would like to do these changes.
> Would you?
> Suggest me If you have any other idea.

**Comment by kunalkeshan** [comment]
Alright, works

- The feedback link works, so this one does not need to be updated.
- The current size is alright, because it's not a heading, it's just conveying that there's some information there. 
- Yes, that works for the alignment.

This issue is specific only to the sem 1 drive link, so keep a focus on that!

**Comment by SAD0XER** [comment]
> Alright, works
> 
> * The feedback link works, so this one does not need to be updated.
> * The current size is alright, because it's not a heading, it's just conveying that there's some information there.
> * Yes, that works for the alignment.
> 
> This issue is specific only to the sem 1 drive link, so keep a focus on that!

Relax, I was just discussing it here about that.

**Comment by kunalkeshan** [comment]
Oh cool, np XD. the `-` is added for headings which contain emojis. It's working when I'm trying over here when you open the `README.md` page directly. 

![image](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/68579547/ea310bdf-76cf-4f54-b416-027cdc4b12ea)

**Comment by SAD0XER** [comment]
**Yes. You are right!**

But Suppose, someone is reading **README.md** and the `Table of Content` & he wants to go directly to that `Feedback` section.

So, now if I click on the `/#feedback` link, it is not redirecting to that section but if I open that link in a **new tab** then it shows directly the `Feedback` section.

**Here my POV is that if I click on `Feedback` then it should redirect to that respective section as other `Table of Content` elements are doing.**

**Comment by SAD0XER** [comment]
Have you forgotten to close this issue or Need to do more in this?

**Comment by kunalkeshan** [comment]
Yep looks like that 😅
