### ISSUE TITLE
Code of this website 

### ISSUE THREAD

**Issue by Saurabh7966** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#121]
Can you make open source for this website?

**Comment by kunalkeshan** [comment]
> Can you make open source for this website?

Hey @Saurabh7966, the code for this repo is **open source**. 
The website is built using React and is present on the [`client`](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/tree/client) branch. It is deployed using Netlfiy and is currently hosted at https://notes.kunalkeshan.dev.
