### ISSUE TITLE
`Client` - Update Button to Anchor Element in Contribute Requests Page

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#122]

**Comment by SAD0XER** [comment]
Hello @kunalkeshan, can you assign this issue to me? I love to solve it.
I want to fix it.

**Comment by kunalkeshan** [comment]
Hey @SAD0XER, sure, you can take this up. 

Can you try to find a fix that makes sure that future links will not overflow as well? Thanks!

**Comment by SAD0XER** [comment]
> Hey @SAD0XER, sure, you can take this up. 
> 
> Can you try to find a fix that makes sure that future links will not overflow as well? Thanks!

Hey @kunalkeshan ,
Are you talking about this _anchor_ element?⬇️⬇️
![Screenshot_20231004-103434-1.jpg](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/79737447/57352fbc-7605-49c2-8cc7-afe90a81c46d)

You are saying that it need to change to button, am I right?

**Comment by kunalkeshan** [comment]
> Hey @kunalkeshan , Are you talking about this _anchor_ element?⬇️⬇️ ![Screenshot_20231004-103434-1.jpg](https://user-images.githubusercontent.com/79737447/272467550-57352fbc-7605-49c2-8cc7-afe90a81c46d.jpg)
> 
> You are saying that it need to change to button, am I right?

Hey there, it's about the yellow buttons that are part of the cards in the [contribute requests](https://notes.kunalkeshan.dev/#/contribute-requests) page. Those buttons needs to converted as anchor tags while keeping the same styles persisted.

![image](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/68579547/16738fb2-7c3c-4362-ae2a-9b1f9706aa4e)
