### ISSUE TITLE
Semester 2: BEEE Lab Full Notes Required

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#46]
Will be appreciated if it includes the following:

- Pre and Post-Lab Question and answers.
- Simulation Output
- Result
- Table Readings
- Graphs

**Comment by thelordzeus** [comment]
I can help with this. I have good quality notes

**Comment by kunalkeshan** [comment]
> I can help with this. I have good quality notes

Alright, go forward with it.
