### ISSUE TITLE
Semester 2: Physics Full Lab Notes Required

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#47]
Will be appreciated if it includes the following:

- Pre and Post-Lab Question and answers.
- Simulation Output
- Result
- Table Readings
- Graphs

**Comment by thelordzeus** [comment]
I can Help with this.

**Comment by kunalkeshan** [comment]
> I can Help with this.

Awesome, go forward with it.

**Comment by aryanraj2713** [comment]
I can help

**Comment by kunalkeshan** [comment]
> I can help

Perfect @aryanraj2713, go ahead.
