### ISSUE TITLE
Semester 1: Chemistry Full Lab Notes Required

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#48]
Will be appreciated if it includes the following:

- Pre and Post-Lab Question and answers.
- Simulation Output
- Result
- Table Readings
- Graphs

**Comment by thelordzeus** [comment]
I would like to contribute by providing handwritten notes in this subject.

**Comment by kunalkeshan** [comment]
> I would like to contribute by providing handwritten notes in this subject.

Awesome, you can refer to the [CONTRIBUTING.md](/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/blob/main/CONTRIBUTING.md) guide to know how to add them. Else refer to the discussions to find the YouTube video on how to do it.
