### ISSUE TITLE
Client: Improve Issues card styling in Issues Page

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#58]
Use this for reference: https://resources.kunalkeshan.dev/#/issues

**Comment by SAD0XER** [comment]
@kunalkeshan, I think this issue is resolved.
Issue cards are the same as you have given in the reference link.

**Comment by kunalkeshan** [comment]
Yea Ig, the main issues where the link and image overflow which you helped fix in past issues.
