### ISSUE TITLE
Client: Single Semester Page

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#59]
Page: https://notes.kunalkeshan.dev/#/notes/semester-3

In mobile view, really large course names are overflowing. Fix by adding an overflow none, or text wrap at mobile width.

**Comment by SAD0XER** [comment]
I will fix this #59 issue but what about that link is overflowing in issue cards? :sweat_smile:

![image](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/79737447/548b6502-df68-404e-b24e-81119e51fc9c)

**Comment by kunalkeshan** [comment]
I guess a max-width and a text-wrap should do the trick for this.
