### ISSUE TITLE
Client: Options For each course Card

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#70]
The menu options should have the following options,

- Report - Redirect to a new issue.
- Edit - Open the source file of the following semester.

**Comment by SAD0XER** [comment]
![Screenshot 2023-10-30 122313](https://github.com/kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24/assets/79737447/f819bde0-4fba-4aa4-8dc0-0acc25d536db)

# Please refer this screenshot for following:
- Q1. The **Red** area I have highlighted is a *Course Card* or **Blue** area is a *Course Card*?

- Q2. Where should add the menu options? on **purple** spots or **green** spots?

**Comment by kunalkeshan** [comment]
1. Red is the Individual Course card, and blue is the heading section for which semester the user is currently viewing.
2. I don't think menu options are required. There are not going to be any more additions I guess. Do you have any more in your mind? If you're worried about responsiveness they already have flex-wrap, and it's comfortable to use as it is.

**Comment by SAD0XER** [comment]
> 1. Red is the Individual Course card, and blue is the heading section for which semester the user is currently viewing.
> 2. I don't think menu options are required. There are not going to be any more additions I guess. Do you have any more in your mind? If you're worried about responsiveness they already have flex-wrap, and it's comfortable to use as it is.

Understood!

If menu option is not required then I think this issues need to close, what do you think? :thinking:

**Comment by kunalkeshan** [comment]
I have no idea what I had in mind when I opened this one year ago lol.
