### ISSUE TITLE
Client: Height issues for Project Contributors comtainer

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#74]
![Screenshot_20221017-144828.jpg](https://user-images.githubusercontent.com/68579547/196140380-1469e604-d81f-44f3-a5cb-05f47fe4b02b.jpg)

**Comment by SAD0XER** [comment]
Hello @kunalkeshan, *Here is one question about this project/issue.*

I observed the files of this `client` branch for this issue.
So, my question is why you've made so many files for different-different sections on the landing/home page?
I mean, why don't you write all the code in one file? :sweat_smile:

My point is while fixing any issue, we don't need to look for separate files for each section. Within a single landing page, we can solve and fix that issue. That's why.

**I want to hear from you, what is the reason.**

**Comment by kunalkeshan** [comment]
Hey @SAD0XER. 

You can keep all the sections in the single page, and it's not wrong either. I'd like you think of this from a solo perspective first, it's a project that only you'll be working on and therefore you will know where which part of the page does what. 

Now imagine you're working in a team, with people whom you don't know (basically OS). If everyone works on the same page, there's bound to be confusion and lots of merge conflicts. 

Splitting that one single page into sections and keeping it in different files help keep the [separation of concerns](https://stackoverflow.com/questions/10620496/separation-of-concerns-vs-loose-coupling#:~:text=Separation%20of%20concerns%20is%20about%20separating%20different%20aspects%20of%20functionality%20in%20different%20components.%20You%20can%20separate%20different%20aspects%2C%20but%20make%20components%20tight%20coupled%20(i.e.%20use%20concrete%20classes%20instead%20of%20abstractions).). Naming the sections/components in the way they're being used helps split to the code into small chunks so people can work on that part which they know the issue is at or one they've been assigned.

**Comment by kunalkeshan** [comment]
Also, as an example think that in a restaurant's kitchen, you'll have different people working in different stations right? One person to chop all the vegetables, one to handle the stove, one to decorate the plate and so on. 

You don't have all of them doing their work in one single place, they have it separated for their specific purpose. It's the same way with code, while it's possible to do it in a single place, it's bound to become messy and unreadable as the project grows and the complexity increases.

**Comment by SAD0XER** [comment]
**Wonderful Explanation. As always, It cleared my doubt as well :smile:**
---

Talking about this Height Issue, how can I solve this?

I tried to fix it in inspect mode, but it didn't work.

When I fix *Desktop UI*, *Mobile UI* worsens and vice versa.

Would you happen to have any idea how to fix this? I am ready to fix this.

**Comment by kunalkeshan** [comment]
closed in #142
